---
title: Introduction to Git
author: Jeffrey Leek
always_allow_html: 'yes'
---

## What is Version Control?

<q>Version control is a system that records changes to a file or set of files over time so that you can recall specific versions later.</q>

[http://git-scm.com/book/en/Getting-Started-About-Version-Control](http://git-scm.com/book/en/Getting-Started-About-Version-Control)


## What is Version Control?

* Many of us constantly create something, save it, change it, then save it again
* Version (or revision) control is a means of managing this process in a reliable and efficient way
* Especially important when collaborating with others

[http://en.wikipedia.org/wiki/Revision_control](http://en.wikipedia.org/wiki/Revision_control)


## What is Git?

<q>Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.</q>

[http://git-scm.com/](http://git-scm.com/)


## What is Git?

* Created by the same people who developed Linux
* The most popular implementation of version control today
* Everything is stored in local repositories on your computer
* Operated from the command line

[http://git-scm.com/book/en/Getting-Started-A-Short-History-of-Git](http://git-scm.com/book/en/Getting-Started-A-Short-History-of-Git)
